
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Users/Showmik/.gemini/antigravity-cli/bin/"
      - "C:/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Ninja/"
      - "H:/hugo/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/Python313/Scripts/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/PowerShell/7/"
      - "C:/Users/Showmik/AppData/Local/Programs/Python/Python313/Scripts/"
      - "C:/Espressif/tools/idf-python/3.11.2/"
      - "C:/Espressif/tools/idf-git/2.44.0/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "H:/Program Files/Void/bin/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/nodejs/"
      - "C:/Users/Showmik/AppData/Local/agy/bin/"
      - "C:/Users/Showmik/AppData/Local/Programs/cursor/resources/app/codeBin/"
      - "C:/Users/Showmik/AppData/Roaming/Python/Python313/Scripts/"
      - "C:/Program Files/PlasticSCM5/server/"
      - "C:/Program Files/PlasticSCM5/client/"
      - "C:/Program Files/Calibre2/"
      - "C:/ninja/"
      - "C:/Program Files/Microsoft VS Code/bin/"
      - "C:/Users/Showmik/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/Showmik/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/Showmik/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/Showmik/AppData/Local/Microsoft/WinGet/Packages/Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "C:/Users/Showmik/AppData/Local/Programs/oh-my-posh/"
      - "C:/Users/Showmik/AppData/Local/Programs/oh-my-posh/bin/"
      - "C:/adb/"
      - "C:/Users/Showmik/.dotnet/tools/"
      - "C:/Users/Showmik/AppData/Local/Programs/cursor/resources/app/bin/"
      - "H:/Program Files/Windsurf/bin/"
      - "C:/Users/Showmik/AppData/Roaming/npm/"
      - "C:/Users/Showmik/AppData/Local/Programs/Antigravity/bin/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Users/Showmik/.gemini/antigravity-cli/bin/mingw32-make.exe.com"
      - "C:/Users/Showmik/.gemini/antigravity-cli/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe"
      - "C:/Ninja/mingw32-make.exe.com"
      - "C:/Ninja/mingw32-make.exe"
      - "H:/hugo/mingw32-make.exe.com"
      - "H:/hugo/mingw32-make.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/mingw32-make.exe.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Program Files/Python313/Scripts/mingw32-make.exe.com"
      - "C:/Program Files/Python313/Scripts/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/Program Files/PowerShell/7/mingw32-make.exe.com"
      - "C:/Program Files/PowerShell/7/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/Programs/Python/Python313/Scripts/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/Programs/Python/Python313/Scripts/mingw32-make.exe"
      - "C:/Espressif/tools/idf-python/3.11.2/mingw32-make.exe.com"
      - "C:/Espressif/tools/idf-python/3.11.2/mingw32-make.exe"
      - "C:/Espressif/tools/idf-git/2.44.0/mingw32-make.exe.com"
      - "C:/Espressif/tools/idf-git/2.44.0/mingw32-make.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe"
      - "H:/Program Files/Void/bin/mingw32-make.exe.com"
      - "H:/Program Files/Void/bin/mingw32-make.exe"
      - "C:/Program Files/Git/cmd/mingw32-make.exe.com"
      - "C:/Program Files/Git/cmd/mingw32-make.exe"
      - "C:/Program Files/nodejs/mingw32-make.exe.com"
      - "C:/Program Files/nodejs/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/agy/bin/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/agy/bin/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/Programs/cursor/resources/app/codeBin/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/Programs/cursor/resources/app/codeBin/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Roaming/Python/Python313/Scripts/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Roaming/Python/Python313/Scripts/mingw32-make.exe"
      - "C:/Program Files/PlasticSCM5/server/mingw32-make.exe.com"
      - "C:/Program Files/PlasticSCM5/server/mingw32-make.exe"
      - "C:/Program Files/PlasticSCM5/client/mingw32-make.exe.com"
      - "C:/Program Files/PlasticSCM5/client/mingw32-make.exe"
      - "C:/Program Files/Calibre2/mingw32-make.exe.com"
      - "C:/Program Files/Calibre2/mingw32-make.exe"
      - "C:/ninja/mingw32-make.exe.com"
      - "C:/ninja/mingw32-make.exe"
      - "C:/Program Files/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/GitHubDesktop/bin/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/GitHubDesktop/bin/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/Microsoft/WinGet/Packages/Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/Microsoft/WinGet/Packages/Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/Programs/oh-my-posh/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/Programs/oh-my-posh/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/Programs/oh-my-posh/bin/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/Programs/oh-my-posh/bin/mingw32-make.exe"
      - "C:/adb/mingw32-make.exe.com"
      - "C:/adb/mingw32-make.exe"
      - "C:/Users/Showmik/.dotnet/tools/mingw32-make.exe.com"
      - "C:/Users/Showmik/.dotnet/tools/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/Programs/cursor/resources/app/bin/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/Programs/cursor/resources/app/bin/mingw32-make.exe"
      - "H:/Program Files/Windsurf/bin/mingw32-make.exe.com"
      - "H:/Program Files/Windsurf/bin/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Roaming/npm/mingw32-make.exe"
      - "C:/Users/Showmik/AppData/Local/Programs/Antigravity/bin/mingw32-make.exe.com"
      - "C:/Users/Showmik/AppData/Local/Programs/Antigravity/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "C:/Users/Showmik/.gemini/antigravity-cli/bin"
        - "C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Ninja"
        - "H:\\hugo"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA app\\NvDLISR"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Python313\\Scripts"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\PowerShell\\7\\"
        - "C:\\Users\\Showmik\\AppData\\Local\\Programs\\Python\\Python313\\Scripts"
        - "C:\\Espressif\\tools\\idf-python\\3.11.2"
        - "C:\\Espressif\\tools\\idf-git\\2.44.0"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "H:\\Program Files\\Void\\bin"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\Showmik\\AppData\\Local\\agy\\bin"
        - "c:\\Users\\Showmik\\AppData\\Local\\Programs\\cursor\\resources\\app\\codeBin"
        - "C:\\Users\\Showmik\\AppData\\Roaming\\Python\\Python313\\Scripts"
        - "C:\\Program Files\\PlasticSCM5\\server"
        - "C:\\Program Files\\PlasticSCM5\\client"
        - "C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\Calibre2\\"
        - "C:\\ninja"
        - "H:\\hugo"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA app\\NvDLISR"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Microsoft VS Code\\bin"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\PowerShell\\7\\"
        - "C:\\Program Files\\Python313\\Scripts"
        - "C:\\Users\\Showmik\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Showmik\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\Users\\Showmik\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\Showmik\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "C:\\Users\\Showmik\\AppData\\Local\\Programs\\oh-my-posh\\"
        - "C:\\Users\\Showmik\\AppData\\Local\\Programs\\oh-my-posh\\bin"
        - "C:\\adb"
        - "C:\\Users\\Showmik\\.dotnet\\tools"
        - "C:\\Users\\Showmik\\AppData\\Local\\Programs\\cursor\\resources\\app\\bin"
        - "H:\\Program Files\\Windsurf\\bin"
        - "C:\\Users\\Showmik\\AppData\\Roaming\\npm"
        - "C:\\Users\\Showmik\\AppData\\Local\\Programs\\Antigravity\\bin"
...
