[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
lib_archive = false

extra_scripts = pre:pre_build.py

lib_deps =
    olikraus/U8g2@^2.35.7