Import("env")
import os

print("\n--- Generating GameIncludes.h ---")

games_dir = env.subst("$PROJECT_DIR/lib")
includes_file = env.subst("$PROJECT_DIR/src/GameIncludes.h")

headers = []
# Find all .h files in lib/
for root, dirs, files in os.walk(games_dir):
    # Skip the Core engine directory
    if os.path.basename(root) == "Core":
        continue
        
    for file in files:
        # We assume the main game header ends with "Game.h"
        # e.g. SpaceInvadersGame.h, TinyRogueGame.h
        if file.endswith("Game.h"):
            headers.append(file)

with open(includes_file, "w") as f:
    f.write("// AUTO-GENERATED BY pre_build.py\n")
    f.write("// Do not edit this file manually.\n")
    f.write("#pragma once\n\n")
    for header in sorted(headers):
        f.write(f'#include "{header}"\n')
        print(f"Added: {header}")

print("---------------------------------\n")