#pragma once
#include <Arduino.h>

// Player: 7x5 pixels
static const uint8_t PROGMEM spr_si_player[5] = {
    0x08, // ...X....
    0x1C, // ..XXX...
    0x3E, // .XXXXX..
    0x7F, // XXXXXXX.
    0x7F  // XXXXXXX.
};

// Alien 1 (Squid): 5x5 pixels
static const uint8_t PROGMEM spr_si_alien1[5] = {
    0x70, // .XXX....
    0xF8, // XXXXX...
    0xA8, // X.X.X...
    0xF8, // XXXXX...
    0x50  // .X.X....
};

// Alien 2 (Crab): 5x5 pixels
static const uint8_t PROGMEM spr_si_alien2[5] = {
    0x50, // .X.X....
    0xF8, // XXXXX...
    0xA8, // X.X.X...
    0x70, // .XXX....
    0xA8  // X.X.X...
};