// AUTO-GENERATED BY pre_build.py
// Do not edit this file manually.
#pragma once

#include "BrickBreakerGame.h"
#include "ChessGame.h"
#include "DinoGame.h"
#include "PongGame.h"
#include "SnakeGame.h"
#include "SpaceInvadersGame.h"
#include "TinyRogueGame.h"
