/**
 * Game Console Firmware — Main Entry Point
 *
 * Registering a new game:
 *   Just drop the game's folder into lib/ and include REGISTER_GAME(YourGame) in its .cpp.
 *   No need to modify this file!
 *
 * Build: PlatformIO, Arduino framework, ESP32-S3
 */

#include <Arduino.h>
#include "OS.h"
#include "GameIncludes.h" // Auto-generated by pre_build.py

// ─── Global instances ────────────────────────────────────────────────────────
OS os;

// ─── Setup ───────────────────────────────────────────────────────────────────
void setup() {
    os.begin();
    os.run();   // never returns
}

void loop() {}  // OS::run() never returns; loop() never called